# Generated by Django 4.1 on 2023-02-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_exchange', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
