# Generated by Django 4.1 on 2023-02-11 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_exchange', '0003_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='photo',
            new_name='image_path',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='user',
            new_name='name',
        ),
        migrations.AddField(
            model_name='picture',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
