# Generated by Django 4.1 on 2023-02-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_exchange', '0005_alter_picture_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='tag',
            field=models.CharField(default='default', max_length=2000),
        ),
    ]
